### ISSUE TITLE
SERVER: Clients can `PRIVMSG` themselves

### ISSUE THREAD

**Issue by dlbltv** [dlbltv/ft_irc#10]
I noticed clients can message themselves. Should we let this happen? @dlbltv
![Image](https://github.com/user-attachments/assets/162af0c0-2c0a-46bf-bb37-3acf31f9a185)
![Image](https://github.com/user-attachments/assets/6607ef41-aabe-49a9-bca3-b9cdc56bfff9)

**Comment by mortinso** [comment]
Awesome, I think we can mark this issue as closed then!
