### ISSUE TITLE
When a user creates a channel, they should get operator status automatically

### ISSUE THREAD

**Issue by mortinso** [dlbltv/ft_irc#21]

**Comment by mortinso** [comment]
I don't know how we're supposed to handle operators leaving the channel:
* If all operators leave, does the channel lose the ability to have operators?

**Comment by dlbltv** [comment]
@mortinso 

"When a user creates a channel, they should get operator status automatically" - I added that aleaady, because I'm doing the MODE command now and it needed that in there. I'll try to finish it today. I have to fix the leaks.

Regarding the second question. I think let's try to make the oldest member become an operator.

**Comment by mortinso** [comment]
> @mortinso
> 
> "When a user creates a channel, they should get operator status automatically" - I added that aleaady, because I'm doing the MODE command now and it needed that in there. I'll try to finish it today. I have to fix the leaks.
> 
> Regarding the second question. I think let's try to make the oldest member become an operator.

Awesome! I think I can easily do that tomorrow

**Comment by mortinso** [comment]
> @mortinso I think I'm done with MODE. It will need some more work when we make the TOPIC command.
> 
> How do you think we should do it? You go to my branch and test it, because maybe I didn't think of some cases. And only then we'll merge it if main, or I'll maerge the btanch with testing and we can both test it here. Why I'm asking, since you're good at testing. You always find something that's not obvious.

@dlbltv  Create a pull request into main and tomorrow I'll git switch to the branch and try to break it hehe. If everything works then we can merge the request. 
> Also, when we are done with this command, you can continue your changes - assign operator to the oldest member. I mean, so we don't have any conflicts when we're merging.

For sure! I'll keep the `operator_status` branch on hold until we merge `mode_command` into `main`
